Paulo/orb deploy lambda
Cyber4All/orb pull request #14
Opened 2022-04-18 20:55 UTC by pmanal1

Finished jobs/deploy-lambda
Should I merge into Josue's orbUpdates branch (josue/orbUpdates) or shall I leave it to merge into main?

2022-04-19 11:14 UTC, JosueMolinaMorales requested changes
Just a couple things. Great Job!

2022-04-19 11:14 UTC, JosueMolinaMorales commented on src/jobs/deploy-lambda.yml
> +  aws-region:
Put required parameters at the top. (those that dont have a default value) and add a comment separating required and non required

2022-04-19 11:14 UTC, JosueMolinaMorales commented on src/jobs/deploy-lambda.yml
> +        aws lambda update-function-code --function-name <<parameters.lambda-function-name>>
There are a couple of ways to update a lambda function. Uploading a zip or a docker image. You should talk to chris and see if we want to implement both or just one. Here is the aws cli reference: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/update-function-code.html

2022-04-19 18:33 UTC, Cwagne17 commented on .circleci/config.yml
> +            branches:
lets remove this and instead just get rid of the commands and jobs being tested in test-deploy.yml

2022-04-19 18:33 UTC, Cwagne17 commented on src/@orb.yml
> +  slack: circleci/slack@4.9.3
lets add the URL to this version on the orb registry

2022-04-19 18:34 UTC, Cwagne17 commented on src/commands/setup-docker.yml
> +  - docker/check:
If we base off of Josue's branch with the setup-docker changes, then this should be fine

2022-04-19 18:34 UTC, Cwagne17 commented on src/commands/tag-repo.yml
> +  - run:
rebase to Josue's branch

2022-04-19 18:35 UTC, Cwagne17 commented on src/message_templates/deploy_aws_success.json
> +{
If we are going to use the same information as mine, then lets rebase off of my branch

2022-04-19 18:35 UTC, Cwagne17 commented on src/jobs/deploy-lambda.yml
> +
lets remove the spaces in between each of the parameters

2022-04-19 18:45 UTC, Cwagne17 requested changes
Rebase to the deploy_ecs branch I have up so you can inherit Josue's changes, as well as mine.
Also remove support for containers. This will require us to transition to ECR which we don't want to do.
Lastly, change some of the parameter names to match the lambda CLIv2 and add steps to build the app with only production dependencies and zip it all up.

2022-04-19 18:45 UTC, Cwagne17 commented on src/jobs/deploy-lambda.yml
> +      The semantic version of the project to be deployed
```suggestion
      The semantic version of the project trying to be deployed
      https://semver.org/spec/v2.0.0.html
```

2022-04-19 18:45 UTC, Cwagne17 commented on src/jobs/deploy-lambda.yml
> +        if [[ <<parameters.lambda-package-type>> == "Zip" ]]
instead of using a bash if statement. Lets use the circleci when:

2022-04-19 18:45 UTC, Cwagne17 commented on src/jobs/deploy-lambda.yml
> +  lambda-package-value:
instead of package value just have image-uri and zip-file so it makes more sense.

2022-04-19 18:45 UTC, Cwagne17 commented on src/jobs/deploy-lambda.yml
> +          aws lambda update-function-code --function-name <<parameters.lambda-function-name>> --image-uri <<parameters.lambda-package-value>>
We won't need the image-uri because then we would have to use ECR instead of docker hub

2022-04-19 18:45 UTC, Cwagne17 commented on src/jobs/deploy-lambda.yml
>  steps:
We will want to tag the repo as well.

2022-04-19 18:45 UTC, Cwagne17 commented on src/jobs/deploy-lambda.yml
>  steps:
We also need a step to build the application then zip it up.

2022-04-19 20:39 UTC, StarChaser44 reviewed
Chris has some comments

2022-04-21 11:57 UTC, pzalep1 reviewed
Great work! Once Chris's comments are addressed this should be good to go.

2022-04-21 13:20 UTC, EVogel1999 reviewed
Looks good after everyone's comments are addressed.

2022-04-22 16:44 UTC, Cwagne17 requested changes

2022-04-25 13:43 UTC, AStoerkel1 requested changes
looks good. just make sure you're using the correct keys for lambda from circleci

2022-04-25 13:43 UTC, AStoerkel1 commented on src/jobs/deploy-lambda.yml
> +      Access key for MACHINE_AWS_ECS
```suggestion
      Access key for MACHINE_AWS_LAMBDA
```

2022-04-25 13:43 UTC, AStoerkel1 commented on src/jobs/deploy-lambda.yml
> +      Secret Key for Machine_AWS_ECS
```suggestion
      Secret Key for Machine_AWS_LAMBDA
```

2022-04-25 14:05 UTC, Cwagne17 commented on src/jobs/deploy-lambda.yml
> +      The semantic version of the project trying to be deployed
```suggestion
      The semantic version of the project trying to be deployed
      https://semver.org/spec/v2.0.0.html
```

2022-04-25 14:06 UTC, Cwagne17 commented on src/jobs/deploy-lambda.yml
> +      Specify the region for aws
```suggestion
      Env var of AWS region to operate in
      (defaults to AWS_REGION_N_VA)
```

2022-04-25 14:11 UTC, Cwagne17 commented on src/jobs/deploy-lambda.yml
> +      aws-secret-access-key: <<parameters.aws-secret-access-key-id>>
```suggestion
      aws-secret-access-key: <<parameters.aws-secret-access-key>>
```

2022-04-26 13:22 UTC, pmanal1 commented on src/jobs/deploy-lambda.yml
> +        aws lambda update-function-code --function-name <<parameters.function-name>> --zip-file <<parameters.zip-file>>
I tested the zip command on my machine and it looks like it places the new zip file in the current directory (where you run the command from). I don't think this should change the code unless the job changes directories for some reason. What do you think?

2022-04-26 15:03 UTC, EVogel1999 approved these changes

2022-04-27 12:18 UTC, JosueMolinaMorales approved these changes

2022-04-27 13:22 UTC, pzalep1 approved these changes

2022-04-27 13:41 UTC, merged