Josue/orb updates
Cyber4All/orb pull request #8
Opened 2022-04-12 14:48 UTC by JosueMolinaMorales

This PR completes part of [8276](https://app.shortcut.com/clarkcan/story/8276/implement-circleci-orb) and [8647](https://app.shortcut.com/clarkcan/story/8647/implement-command-tag-repo)

For tagging, i believe no authentication is necessary because the -checkout command would be use before the tag-repo command would be use and looking at the circleci docs about the -checkout command this is what i saw about authentication : `This command will automatically add the required authenticity keys for interacting with GitHub and Bitbucket over SSH`

2022-04-13 13:27 UTC, StarChaser44 submitted a review, later dismissed

2022-04-13 13:29 UTC, EVogel1999 submitted a review, later dismissed

2022-04-13 15:04 UTC, Cwagne17 requested changes
Other the lint requests. Check where the status are failing.

2022-04-13 15:04 UTC, Cwagne17 commented on src/commands/tag-repo.yml
> +    command: |
use >

2022-04-14 15:20 UTC, EVogel1999 approved these changes

2022-04-15 13:38 UTC, Cwagne17 commented on src/commands/setup-aws.yml
>    This command should be used prior to working with aws orbs or cli commands.
We can remove this file with the new insight I posted on Andy's story.

2022-04-15 13:41 UTC, Cwagne17 requested changes
Small requests. Looks good!

2022-04-15 13:41 UTC, Cwagne17 commented on src/commands/setup-docker.yml
> +  - run:
use docker/check not docker cli

2022-04-15 13:41 UTC, Cwagne17 commented on src/commands/tag-repo.yml
> +      Tag being assigned
```suggestion
      The semantic version of the project trying to be deployed
      https://semver.org/spec/v2.0.0.html
```

2022-04-15 13:41 UTC, Cwagne17 commented on src/commands/tag-repo.yml
> +      name: Tag Repo
```suggestion
      name: "Tag $CIRCLE_PROJECT_REPONAME Repository"
```

2022-04-15 13:41 UTC, Cwagne17 commented on src/commands/tag-repo.yml
> +      name: Tag Repo
https://circleci.com/docs/2.0/env-vars/?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--uscan-en-dsa-maxConv-auth-brand&utm_term=g_-_c__dsa_&utm_content=&gclid=Cj0KCQjwr-SSBhC9ARIsANhzu14qQHzsiV1UDPIUlBqyEjQUJqF-y_q74BFkorF2NMYyJ8SI6lYLBR4aAvgoEALw_wcB#built-in-environment-variables

2022-04-18 12:45 UTC, pzalep1 reviewed
After Chris's comments are addressed this looks good!

2022-04-18 14:43 UTC, StarChaser44 reviewed
Build is failing

2022-04-19 12:03 UTC, JosueMolinaMorales commented
> Build is failing

Builds are going to fail since not all job implementations are in main.

2022-04-19 18:47 UTC, Cwagne17 commented on .circleci/config.yml
> +            branches:
lets remove the filter then remove the test-deploy jobs and commands being tested

2022-04-19 18:48 UTC, Cwagne17 commented on src/jobs/deploy-s3.yml
> +#required parameters
```suggestion
 # Required Parameters
```

2022-04-19 18:48 UTC, Cwagne17 commented on src/jobs/deploy-s3.yml
> +#optional parameters with defaults
```suggestion
 # Not Required Parameters
```

2022-04-19 18:48 UTC, Cwagne17 commented on src/jobs/deploy-s3.yml
> +
can we remove these spaces

2022-04-19 18:50 UTC, Cwagne17 requested changes

2022-04-19 18:50 UTC, Cwagne17 commented on src/jobs/deploy-s3.yml
> +      command: npm run build --aot --build-optimizer=true --optimization=true --configuration=production
we should change this to ng build 
```suggestion
      command: ng build --aot --build-optimizer=true --optimization=true --configuration=production
```

2022-04-19 20:33 UTC, StarChaser44 reviewed
Chris has some comments

2022-04-20 20:19 UTC, pzalep1 reviewed
Once Chris's comments are addressed this will be good to go!

2022-04-21 13:18 UTC, EVogel1999 reviewed
After everyone's comments are addressed, looks good!

2022-04-22 13:43 UTC, Cwagne17 approved these changes

2022-04-25 14:00 UTC, EVogel1999 submitted a review, later dismissed

2022-04-27 13:19 UTC, pzalep1 submitted a review, later dismissed

2022-04-27 16:48 UTC, Cwagne17 approved these changes

2022-04-27 17:07 UTC, AStoerkel1 approved these changes

2022-04-28 14:40 UTC, merged